### ISSUE TITLE
Error with 3d transform on images

### ISSUE THREAD

**Issue by SilverKnightVGM** [sdaps/sdaps#123]
Hello I was testing how reliable the recognition is with pictures taken from a camera/cellphone and came across the following error:

```
sdaps /tmp/project1 convert --3d-transform /tmp/test1/*.jpg --output /tmp/out.tif
------------------------------------------------------------------------------
- SDAPS -- convert
------------------------------------------------------------------------------
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Traceback (most recent call last):
  File "/usr/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/script.py", line 105, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/cmdline/convert.py", line 64, in convert
    convert_images(cmdline['images'], cmdline['output'], survey.defs.paper_width, survey.defs.paper_height, cmdline['transform'])
  File "/usr/lib/python2.7/dist-packages/sdaps/convert/__init__.py", line 37, in convert_images
    log.warning(_("Could not apply 3D-transformation to image '%s', page %i!") % (filename, page))
AttributeError: 'module' object has no attribute 'warning'
```
Any ideas as to why I am getting this? I tried the same command with the example images provided in the documentation and those work completely fine. Also the problem only happens when I add the "--3d-transform" argument, without it, it proceeds fine but the image is not scanned properly because of skewing. Thanks!

**Comment by benzea** [comment]
First, there is the straight forward bug that it should be log.warn and not log.warning. Could you replace that please? Once you do, you should see which file (and page inside) it is failing on.

Maybe we know more then.

**Comment by benzea** [comment]
Oh, if you just have a skew as in "[shear mapping](https://en.wikipedia.org/wiki/Shear_mapping)", then you should not need a 3D transformation. 

Anyway, the issue will be that one or more of the corner markers are not found. Simply aborting is maybe a bit extreme in that case.

**Comment by SilverKnightVGM** [comment]
Thanks for the quick answer! Fixed it and got this now:

```
$daps /tmp/project1 convert --3d-transform /tmp/test1/*.jpg --output /tmp/out.tif
------------------------------------------------------------------------------
- SDAPS -- convert
------------------------------------------------------------------------------
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Warning: Could not apply 3D-transformation to image '/tmp/test1/P_20180117_163707_copy.jpg', page 0!
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Warning: Could not apply 3D-transformation to image '/tmp/test1/P_20180117_163712_copy.jpg', page 0!

```
And I did try without the 3d transform but the margin was way off without it so it didn't place any of the boxes in the right place.

**Comment by benzea** [comment]
Are you able to share some more details? i.e. failing images and project?

It could be that there are easy fixes, like increasing the search area for the corner markers.

**Comment by SilverKnightVGM** [comment]
I am just testing the software, so I am using everything default, downloaded the .tex example from here https://sdaps.org/Documentation/Tutorial/

Then I printed one copy (2 pages) and took pictures of it, here they are:
![p_20180117_163707_copy](https://user-images.githubusercontent.com/12931586/35109334-70c8239e-fc4c-11e7-95c1-c4a3b88724df.jpg)
![p_20180117_163712_copy](https://user-images.githubusercontent.com/12931586/35109336-70e70dd6-fc4c-11e7-98a7-9499bdb93e14.jpg)

Let me know if you need more details!

**Comment by benzea** [comment]
Haha, I think I always tried this with a camera that has an aspect ratio of 4:3. I am imagining that the huge margins at the top/bottom are the issue here.

**Comment by benzea** [comment]
If you are up to recompiling SDAPS from source, then you can try changing sdaps/image/image.c, modifying

    gdouble sdaps_corner_mark_search_distance = 50;

to

    gdouble sdaps_corner_mark_search_distance = 100;

or so. That number is in millimetre, but there may also be further issues that the initial estimation for the image resolution is too far off for this to actually work.

Really not sure when I will get around to fixing this.

**Comment by SilverKnightVGM** [comment]
Ah that was it haha. I retook the pictures with a 4:3 ratio and it worked. Also a few days ago I did try compiling it from this source, but it got stuck building for a while so decided to give up on that and just did an apt-get install. Maybe I will try recompiling later with the change suggested for the bigger image. Really appreciate the help!

**Comment by benzea** [comment]
I looked a bit into it, but to be honest, I think the current approach is pretty much a lost cause.

I mean, we could try workarounds, like searching in a larger area, or specifically looking in different regions of the image. Probably can be made to work, but is not great.

It would be much more interesting to find a new approach for the corner mark detection. This could also mean replacing the corner mark with something different.

One thing that we could try is using OpenCV feature detection. If someone is up to it, then I would like to try the following (just a standalone python script would be enough):

1. Create an image of a single corner mark (should be pixel perfect)
2. Create OpenCV ORB feature descriptor for the corner mark: https://docs.opencv.org/3.4.4/d1/d89/tutorial_py_orb.html
3. Try to run the OpenCV matches with that: https://docs.opencv.org/3.4.4/dc/dc3/tutorial_py_matcher.html
4. Try the same thing with a full page image with only the corner marks.

Note that I am not a big fan of adding a hard dependency to OpenCV. That said, it is entirely fine for the initial import conversion.

**Comment by omidraha** [comment]
Hi,

I tried many phones and tablet camera to scan the questionnaires:
Android ([01](https://user-images.githubusercontent.com/397672/51178144-fbea1200-18d6-11e9-83bf-e973b6f07f44.jpg), [02](https://user-images.githubusercontent.com/397672/51178198-1ae8a400-18d7-11e9-96e2-34994fad4558.jpg), [03](https://user-images.githubusercontent.com/397672/51178220-2cca4700-18d7-11e9-9cac-9dc94125fbef.jpg), [04](https://user-images.githubusercontent.com/397672/51178237-3e135380-18d7-11e9-9ca1-bbe342b73a4c.jpg), [05](https://user-images.githubusercontent.com/397672/51178288-597e5e80-18d7-11e9-8e88-5d710067af47.jpg), [06](https://user-images.githubusercontent.com/397672/51178301-63a05d00-18d7-11e9-92fb-99e904170b2b.jpg), [07](https://user-images.githubusercontent.com/397672/51178305-68651100-18d7-11e9-972d-9faa1f3e85c8.jpg), [08](https://user-images.githubusercontent.com/397672/51178328-71ee7900-18d7-11e9-8e45-0887849f59e4.jpg))
IPhone ([09](https://user-images.githubusercontent.com/397672/51178344-7adf4a80-18d7-11e9-98d3-50ed659120cf.jpg), [10](https://user-images.githubusercontent.com/397672/51178355-829eef00-18d7-11e9-9d05-baa13384d819.jpg))
But only one of them (10) detected.
The aspect ratio for phones  and tablet was 4:3
I don't have any problem with scanner ([scanner](https://user-images.githubusercontent.com/397672/51178366-8cc0ed80-18d7-11e9-8087-7e860bf29d04.jpg))

Commands:
```
$ sdaps /ws/sdaps  add --convert 01.jpg
# or using  --3d-transform option
$ sdaps /ws/sdaps  add --convert --3d-transform 01.jpg 
$ sdaps /ws/sdaps recognize
$ sdaps /ws/sdaps csv export

```
Traceback (mxied):
```
Warning: Could not apply 3D-transformation to image '/.....JPG', page 0!
Warning: .....tif, 1: Matrix not recognized.                                      
Warning: Neither .....tif, 0 or DUMMY, -1 has a known rotation!                   
Warning: Neither .....tif, 0 or DUMMY, -1 has a known page number!
Warning: No page number for page .....tif, 0 exists.
Warning: Got a wrong survey ID (.....tif, 0)! It is None, but should be 4261678183.
```

Sdaps prj: ([sdaps.zip](https://github.com/sdaps/sdaps/files/2759503/sdaps.zip))
