### ISSUE TITLE
Troubleshooting incompatibilities between old and new sdaps

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#144]
Greetings,
I am trying to get a colleague to compile a survey with sdaps. This person is not tech savvy at all. Compiling the survey (made for old SDAPS with sdaps.cls), he got from sdaps the following
```
------------------------------------------------------------------------------
- SDAPS -- setup
------------------------------------------------------------------------------
Running pdflatex now twice to generate the questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error running "pdflatex" to compile the LaTeX file.
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/setup.py", line 45, in setup
    return setuptex.setup(cmdline['project'], cmdline['questionnaire.tex'], cmdline['additional_questions'], cmdline['add'])
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/__init__.py", line 108, in setup
    raise AssertionError('PDF file not generated')
AssertionError: PDF file not generated
```
Such a message is not understandable by many users. I had to point him to look for questionnaire.log and send it to me (as he is not able to understand it either). It turns out that LaTeX does not find sdaps.cls.

I suspect that the user installed a too recent version of sdaps. I wanted to ask him the output of ```sdaps --version``` but it appears that sdaps lacks such a feature.

It also would be nice if sdaps would print a error message like the following

> If questionnaire.log contains a line ! LaTeX Error: File `sdaps.cls' not found., it probably means that your questionnaire is written for an earlier version of sdaps. Modern versions of sdaps do not have a sdaps.cls anymore. You can either upgrade your questionnaire to make it work with this version of sdaps or downgrade your sdaps installation to version XXX.

Indeed, that their sdaps could be too recent is certainly not what a user would think about.

**Comment by benzea** [comment]
We can't really list all the possibly errors. What we would need is some code to extract the relevant errors from the LaTeX log file.
