### ISSUE TITLE
Problems with Reorder: Survey' object has no attribute 'sheets

### ISSUE THREAD

**Issue by tux4ever42** [sdaps/sdaps#168]
Hey together,

for some reason I get a problem when I try to reorder my sheets. Everything else works fine.

All the best
 Max

`....e$ sdaps reorder <projectDir>

 SDAPS -- reorder

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 110, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/reorder.py", line 41, in reorder
    return reorder.reorder(survey)
  File "/usr/lib/python3/dist-packages/sdaps/reorder/__init__.py", line 48, in reorder
    for sheet in survey.sheets[:]: # Use a flat copy to iterate over
AttributeError: 'Survey' object has no attribute 'sheets'
`

**Comment by benzea** [comment]
Hah, that probably got broken a few versions back … it looks like fallout from the data storage rework to use sqlite internally.

**Comment by tux4ever42** [comment]
Now I have a similar problem with _gui_. Any ideas how to fix this?

All the best
Max

``` SDAPS -- gui
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/gui/widget_buddies.py", line 150, in toggled_verified_cb
    self._current_image.verified = widget.get_active()
  File "/usr/lib/python3/dist-packages/sdaps/model/sheet.py", line 201, in __setattr__
    self.sheet.survey.questionnaire.notify_data_changed(None, None, attr, old_value)
  File "/usr/lib/python3/dist-packages/sdaps/model/questionnaire.py", line 85, in notify_data_changed
    func(self, qobj, dobj, name, old_value)
  File "/usr/lib/python3/dist-packages/sdaps/gui/widget_buddies.py", line 49, in data_changed
    self.sync_state()
  File "/usr/lib/python3/dist-packages/sdaps/gui/widget_buddies.py", line 125, in sync_state
    review_comment = self.obj.survey.sheet.review_comment if self.obj.survey.sheet.review_comment else ''
AttributeError: 'Sheet' object has no attribute 'review_comment'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 118, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/gui.py", line 43, in gui
    return gui.gui(survey, cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/gui/__init__.py", line 69, in gui
    MainWindow(provider).run()
  File "/usr/lib/python3/dist-packages/sdaps/gui/__init__.py", line 221, in __init__
    self.update_ui()
  File "/usr/lib/python3/dist-packages/sdaps/gui/__init__.py", line 314, in update_ui
    self.provider.survey.questionnaire.widget.sync_state(self.provider.image)
  File "/usr/lib/python3/dist-packages/sdaps/gui/widget_buddies.py", line 125, in sync_state
    review_comment = self.obj.survey.sheet.review_comment if self.obj.survey.sheet.review_comment else ''
AttributeError: 'Sheet' object has no attribute 'review_comment'
```

**Comment by benzea** [comment]
That is a completely independent issue, could you open a new issue for it?

Without having looked at it much, it should be quite simple fix. i.e. fallout from the addition of the "review_comment", I suspect missing migration code (please include info as to whether you upgrade SDAPS after creating the project in the new issue).

**Comment by tux4ever42** [comment]
Copied into a new issue.

**Comment by tux4ever42** [comment]
Is there something new about the `AttributeError: 'Survey' object has no attribute 'sheets'` -Problem? I still can't use `reorder`.

**Comment by benzea** [comment]
Hey, I pushed a fix. I am pretty sure that it works correctly, but it would be great if someone tests it to make sure it works correctly. So  please make a copy of the project first before trying it!
