### ISSUE TITLE
'Sheet' object has no attribute 'review_comment'-Error when using gui

### ISSUE THREAD

**Issue by tux4ever42** [sdaps/sdaps#173]
I have a problem with _gui_. Any ideas how to fix this?

All the best
Max

``` SDAPS -- gui
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/gui/widget_buddies.py", line 150, in toggled_verified_cb
    self._current_image.verified = widget.get_active()
  File "/usr/lib/python3/dist-packages/sdaps/model/sheet.py", line 201, in __setattr__
    self.sheet.survey.questionnaire.notify_data_changed(None, None, attr, old_value)
  File "/usr/lib/python3/dist-packages/sdaps/model/questionnaire.py", line 85, in notify_data_changed
    func(self, qobj, dobj, name, old_value)
  File "/usr/lib/python3/dist-packages/sdaps/gui/widget_buddies.py", line 49, in data_changed
    self.sync_state()
  File "/usr/lib/python3/dist-packages/sdaps/gui/widget_buddies.py", line 125, in sync_state
    review_comment = self.obj.survey.sheet.review_comment if self.obj.survey.sheet.review_comment else ''
AttributeError: 'Sheet' object has no attribute 'review_comment'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 118, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/gui.py", line 43, in gui
    return gui.gui(survey, cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/gui/__init__.py", line 69, in gui
    MainWindow(provider).run()
  File "/usr/lib/python3/dist-packages/sdaps/gui/__init__.py", line 221, in __init__
    self.update_ui()
  File "/usr/lib/python3/dist-packages/sdaps/gui/__init__.py", line 314, in update_ui
    self.provider.survey.questionnaire.widget.sync_state(self.provider.image)
  File "/usr/lib/python3/dist-packages/sdaps/gui/widget_buddies.py", line 125, in sync_state
    review_comment = self.obj.survey.sheet.review_comment if self.obj.survey.sheet.review_comment else ''
AttributeError: 'Sheet' object has no attribute 'review_comment'
```

_Originally posted by @tux4ever42 in https://github.com/sdaps/sdaps/issues/168#issuecomment-492751291_

**Comment by tux4ever42** [comment]
_benzea wrote_:
> That is a completely independent issue, could you open a new issue for it?
> 
> Without having looked at it much, it should be quite simple fix. i.e. fallout from the addition of the "review_comment", I suspect missing migration code (please include info as to whether you upgrade SDAPS after creating the project in the new issue).

Thank you for the fast answer. I believe that SDAPS updates itself automatically when I run aptitude. So it is not unlikely that there has been an update since the project was created. 'apt-cache policy sdaps' said that my current installed version is 1.9.6 -1.

**Comment by benzea** [comment]
Right, then I am very much sure it is a missing data model upgrade/default value. Should be an easy fix, unfortunately I am not sure whether I will get around to look into it before next week.

**Comment by mgwerder** [comment]
I can confirm this issue and I am eagerly waiting for a fix. btw. I am still very happy with SDAPS.

**Comment by tux4ever42** [comment]
Yeah, it'd be great to get a fix as soon as possible. I use SDAPS in my dissertation project and the next data collection is scheduled for tomorrow. Im also very happy with SDAPS. :)

**Comment by benzea** [comment]
That should fix it. Would be great if you can test it and confirm here (please re-open if it is not fixed). Unfortunately it is a bit more involved to test here because I don't have an old project.

**Comment by tux4ever42** [comment]
Yes. Everything is fine with gui now. Thank you!

**Comment by mgwerder** [comment]
Confirm too... Item is fixed with this patch. 

Thanks!
