### ISSUE TITLE
automated processing

### ISSUE THREAD

**Issue by jdanion** [sdaps/sdaps#178]
Hi,

I'm trying to add a new feature for SDAPS in python (instead of a bash script that is less satisfying). I want to make it possible to possible to "watch" into a folder, and when a new scanned sheet is copied, use the SDAPS code that manages the search for the survey ID to move the scanned sheet and run the right command to run "add" and "recognize".

But I'm still looking for the part of the code where SDAPS can identify the survey ID, is it in /model?

**Comment by benzea** [comment]
Nah, it is part of the `recognize` module.

You might get an idea of how to do that from the `sdaps-identify.py` script in the `custom-scripts` directory of the sources (might only be in git). Note that the script may not be working currently due to some changes, but the principle is still the same.

Unfortunately, you *will* need a dummy survey for this. And you will likely need to add the image to this survey temporarily, and then reset the survey again. The sqlite database in the background may be updated because of these operations.

I fear that taking a shortcut there will be complicated, because the APIs are really not designed for that. That said, you could just make a few assumption about your scan (i.e. guess the area that the survey barcode must be in) and call the `sdaps.utils.barcode.read_barcode` method directly.

**Comment by jdanion** [comment]
Here is our first solution

We have added a "watch.py" command in cmdline that works with two arguments, a project folder and a scan folder.
I made a fork to share it

https://github.com/jdanion/sdaps/blob/master/sdaps/cmdline/watch.py

It should not be written in a very pythonic way so feel free to comment / add / change it.

Our next step is to make it work on a repetitive schedule.

**Comment by jdanion** [comment]
Going further with your custom script. I first make a dummy 'watch' survey, then i can process tiff files. But i got an error in recognize due to rotation problem :(

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/anaconda3/lib/python3.7/site-packages/sdaps/cmdline/watch.py", line 124, in watch
    sheet.recognize.recognize()
  File "/anaconda3/lib/python3.7/site-packages/sdaps/recognize/buddies.py", line 85, in recognize
    self.duplex_copy_image_attr(failed_pages, 'rotated', _("Neither %s, %i or %s, %i has a known rotation!"))
  File "/anaconda3/lib/python3.7/site-packages/sdaps/recognize/buddies.py", line 297, in duplex_copy_image_attr
    second = self.obj.images[i + 1]
IndexError: list index out of range

**Comment by jdanion** [comment]
Ok i made some other changes and it works

if someone is interested

https://github.com/jdanion/sdaps/commit/81e0cf5be3909076b0c62f35ab68c059e8596372

i run

sdaps watch -sf "scan folder where pdf/tiff scans  are first commited" -pf "folder with sdaps projects" -rf "folder with stamped-survey/barcode/questionnaire renamed and converted tiff scans are copied" and for the moment a dummy project name (i'm trying to remove this)

**Comment by benzea** [comment]
Right, that does sound useful in general (in particular, the part to do the automatic sorting).

Feel free to ping me about it every once in a while; maybe we can merge this upstream eventually.
