### ISSUE TITLE
codebox and gui

### ISSUE THREAD

**Issue by jdanion** [sdaps/sdaps#181]
Hi,

I'm going deeper into SDAPS use, a LOT of things are working now.

I have an issue when opening gui of a project

"TypeError: Argument 1 does not allow None as a value"

it is reproduced with 

1 a codebox is present in the survey and

2 it fails to recognize due to poor quality and

3 it is the first recognized survey

I don't know where to find and fix it.

**Comment by benzea** [comment]
Don't you get a longer backtrace together with this?

**Comment by jdanion** [comment]
Yes 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/local/lib/python3.7/site-packages/sdaps/script.py", line 118, in decorated_function
    result = function(cmdline)
  File "/usr/local/lib/python3.7/site-packages/sdaps/cmdline/gui.py", line 43, in gui
    return gui.gui(survey, cmdline)
  File "/usr/local/lib/python3.7/site-packages/sdaps/gui/__init__.py", line 69, in gui
    MainWindow(provider).run()
  File "/usr/local/lib/python3.7/site-packages/sdaps/gui/__init__.py", line 221, in __init__
    self.update_ui()
  File "/usr/local/lib/python3.7/site-packages/sdaps/gui/__init__.py", line 314, in update_ui
    self.provider.survey.questionnaire.widget.sync_state(self.provider.image)
  File "/usr/local/lib/python3.7/site-packages/sdaps/gui/widget_buddies.py", line 113, in sync_state
    qobject.widget.sync_state()
  File "/usr/local/lib/python3.7/site-packages/sdaps/gui/widget_buddies.py", line 202, in sync_state
    box.widget.sync_state()
  File "/usr/local/lib/python3.7/site-packages/sdaps/gui/widget_buddies.py", line 376, in sync_state
    self.buffer.set_text(self.obj.data.text)
  File "/usr/local/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 760, in set_text
    Gtk.TextBuffer.set_text(self, text, length)
TypeError: Argument 1 does not allow None as a value

**Comment by jdanion** [comment]
This one is reproduced with two sheets in the project, first with only some "decoration" text in the code box, the second sheet with a well recognized barcode  (i made a csv export to check)

**Comment by benzea** [comment]
Right, that is something I can work with :)

Looks like we just need a special case in the UI here. Please ping me again on the weekend in case I forget and don't have a fix by then.

**Comment by benzea** [comment]
That should do the trick, please reopen if not.
