### ISSUE TITLE
Issue following getting started

### ISSUE THREAD

**Issue by rafael** [sdaps/sdaps#196]
### Description

Hi! I'm following the instructions from the getting started with the canonical installation for ubuntu. I'm using ubuntu 16.04. I think the docs on the page might not be up to date:
```
 sdaps /tmp/sdaps_test_project setup_tex example.tex      
usage: sdaps [-h]
             {add,annotate,boxgallery,convert,cover,csv,gui,ids,info,recognize,reorder,report,report_tex,reset,setup,stamp}
             ...
sdaps: error: argument command: invalid choice: '/tmp/sdaps_test_project' (choose from 'add', 'annotate', 'boxgallery', 'convert', 'cover', 'csv', 'gui', 'ids', 'info', 'recognize', 'reorder', 'report', 'report_tex', 'reset', 'setup', 'stamp')
```

I updated the command to be: 

```
 sdaps setup /tmp/sdaps_test_project sdaps/example.tex
```

It kind of works, but I'm getting the following LaTex error:
```
------------------------------------------------------------------------------
- SDAPS -- setup
------------------------------------------------------------------------------
Running pdflatex now multiple times to generate the questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error running "pdflatex" to compile the LaTeX file.
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/setup.py", line 53, in setup
    cmdline['add'])
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/__init__.py", line 109, in setup
    raise AssertionError('PDF file not generated')
AssertionError: PDF file not genevrated
```

And when I check the log I see:

```
his is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex 2019.12.2)  2 DEC 2019 22:50
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**questionnaire.tex
(./questionnaire.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 9 language(s) loaded.

! LaTeX Error: File `sdaps.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)
```

Any guidance on how to fix this?

**Comment by benzea** [comment]
Yeah, that example currently still assume the stable version … try using the example from the sources.

We are working on it updating the website, hopefully it will not be too long now.
