### ISSUE TITLE
Can't run setup on example.tex

### ISSUE THREAD

**Issue by chrisbio** [sdaps/sdaps#206]
I am trying to run the example in the program I downloaded by the ppa.

I get the following error: 

```
$ sdaps setup ~/Downloads/example-sdaps/project1 example.tex 

- SDAPS -- setup

Running pdflatex now multiple times to generate the questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error running "pdflatex" to compile the LaTeX file.
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/setup.py", line 53, in setup
    cmdline['add'])
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/__init__.py", line 109, in setup
    raise AssertionError('PDF file not generated')
AssertionError: PDF file not generated
```

Anyone know what is the problem?

Thanks,

**Comment by benzea** [comment]
The problem will be that the website is outdated … try the newer example document from git or the distribution package.

/duplicate #196

**Comment by chrisbio** [comment]
Thanks a lot, working now!
