### ISSUE TITLE
SDAPS stamping crashes on some surveys when using UTF-8 encoding in LaTeX

### ISSUE THREAD

**Issue by mgwerder** [sdaps/sdaps#208]
Hi

When stamping an utf-8 encoded latex file with special characters my SDAPS crashes with the following exception:

```bash
------------------------------------------------------------------------------
- SDAPS -- setup
------------------------------------------------------------------------------
Running pdflatex now multiple times to generate the questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error: Caught an Exception while parsing the SDAPS file. The current state is:
Questionnaire

------------------------------------
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/setup.py", line 53, in setup
    cmdline['add'])
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/__init__.py", line 116, in setup
    sdapsfileparser.parse(survey)
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/sdapsfileparser.py", line 56, in parse
    sdaps_data = sdaps_file.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 810: ordinal not in range(128)
```

While I figured out that the following patch solves the issue:
```diff
54c54
<     sdaps_file = open(survey.path('questionnaire.sdaps'))
---
>     sdaps_file = open(survey.path('questionnaire.sdaps'),'r', encoding='utf-8')
```

the issue seems not as easy as it seems. The line immediately after the corrected line states:

```python
# the file is encoded in ascii format
```

I might be mistaken there but is this an illct assumption? The file is encoded in whatever encoding the LaTeX file was as it includes excerpts from this file.

Am I missing something?

Regards
Martin

**Comment by benzea** [comment]
Much better, it is both true and not true at the same time! ;-)

This could be an update of the tex engine. i.e. what used to happen was that the input encoding package implicitly translates UTF-8 characters to their LaTeX macro equivalents. And then those LaTeX macros end up in the file.

Now, I very much prefer just using UTF-8 encode data to be honest. But it is the reason that sdaps has a generated table to convert those macros back to UTF-8 (and back again).

So, I think we just need to change the comment that the file may be ascii encoded + macros or utf-8.
