### ISSUE TITLE
"File not found" even if the file is crearly in the right directory

### ISSUE THREAD

**Issue by ollemarti** [sdaps/sdaps#236]
Hello,
I am using Ubuntu WSL (Windows) for sdaps, because I could not run it in debian (There are working Tutorials for this on the internet).

sdaps always tells me, that the example.pdf of the example project could not be found, but I can assure it is in said directory (I renamed it like a thousand times, restartet a few times, even copied all the files to another directory, etc. still it tells me the following:

sdaps add /mnt/c/Users/myname/sdaps/project_example --convert aaa.pdf
------------------------------------------------------------------------------
- SDAPS -- add
------------------------------------------------------------------------------
Converting input files into a single temporary file.
Error: [Errno 2] File does not exist: 'aaa.pdf'
Error: Running the conversion failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 120, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/add.py", line 112, in add
    convert_images(cmdline['images'], tmp, survey.defs.paper_width, survey.defs.paper_height, cmdline['transform'])
  File "/usr/lib/python3/dist-packages/sdaps/convert/__init__.py", line 29, in convert_images
    for i, (img, filename, page) in enumerate(opencv.iter_images_and_pages(images)):
  File "/usr/lib/python3/dist-packages/sdaps/utils/opencv.py", line 44, in iter_images_and_pages
    raise IOError(errno.ENOENT, _("File does not exist"), filename)
FileNotFoundError: [Errno 2] File does not exist: 'aaa.pdf'

Could it be, that sdaps does not like PDF (This would be weird, because the example-scans are also pdf).

Many thanks, if someone could help, I'm nearly crying...

**Comment by ollemarti** [comment]
I am SOO dumb...it was not clear for me out of the manual, that the PDF to process must be in the current directory while the code gives the directory of the sdaps-project. Sorry and thanks for your precious work.
