### ISSUE TITLE
Python error while "recognize" and "reset"

### ISSUE THREAD

**Issue by AtlosPrime** [sdaps/sdaps#247]
I'm trying to recognize a simple questionnaire, I already done add without problems, but with recognize I get this message: 
```
user@user-virtualbox:~/Desktop$ sdaps recognize \tmp\Projet
------------------------------------------------------------------------------
- SDAPS -- recognize
------------------------------------------------------------------------------
1 sheet
|                                                                |   0% --:--                                                                             Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 126, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/recognize.py", line 57, in recognize
    return recognize.recognize(survey, filter)
  File "/usr/lib/python3/dist-packages/sdaps/recognize/__init__.py", line 32, in recognize
    survey.iterate_progressbar(survey.questionnaire.recognize.recognize, filter)
  File "/usr/lib/python3/dist-packages/sdaps/model/survey.py", line 422, in iterate_progressbar
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sdaps/recognize/buddies.py", line 501, in recognize
    res = self.identify(clean=False)
  File "/usr/lib/python3/dist-packages/sdaps/recognize/buddies.py", line 478, in identify
    self.obj.sheet.recognize.recognize()
  File "/usr/lib/python3/dist-packages/sdaps/recognize/buddies.py", line 83, in recognize
    image.recognize.calculate_rotation()
  File "/usr/lib/python3/dist-packages/sdaps/recognize/buddies.py", line 346, in calculate_rotation
    self.obj.rotated = self.obj.style.get_page_rotation()
  File "/usr/lib/python3/dist-packages/sdaps/recognize/qrcode.py", line 33, in get_page_rotation
    code = self.find_bottom_right_barcode()
  File "/usr/lib/python3/dist-packages/sdaps/recognize/qrcode.py", line 68, in find_bottom_right_barcode
    return read_barcode(self.obj.surface.surface, self.obj.matrix.mm_to_px(),
  File "/usr/lib/python3/dist-packages/sdaps/utils/barcode.py", line 35, in read_barcode
    result = scan(surface, matrix, x, y, width, height, btype)
  File "/usr/lib/python3/dist-packages/sdaps/utils/barcode.py", line 79, in scan
    pbm = image.get_pbm(a1_surface)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

And I tried to reset my project, so I did but i got that message:

```
user@user-virtualbox:~/Desktop$ sdaps reset \tmp\Projet
------------------------------------------------------------------------------
- SDAPS -- reset
------------------------------------------------------------------------------
Removing stored data...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 126, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/reset.py", line 39, in reset
    return reset.reset(survey)
  File "/usr/lib/python3/dist-packages/sdaps/reset/__init__.py", line 32, in reset
    survey.save()
  File "/usr/lib/python3/dist-packages/sdaps/model/survey.py", line 318, in save
    assert sheet is None or (not sheet.dirty and sheet._rowid != -1)
AssertionError
```

Any advice?

**Comment by AtlosPrime** [comment]
If it can helps, here is the [questionnaire](https://ibb.co/cTqH4jc)

**Comment by benzea** [comment]
Well, OK, the `reset` issue likely a real error that can happen if images were added but `recognize` did not run through.

Though, the main issue is a simple compile fix for the python module. i.e. commit 51d1072185223f5e48512661e2c1e8399d63e876 and 60278062fcd4227331269d447408385584af704d (though there are probably more relevant fixes).

**Comment by AtlosPrime** [comment]
Thank you for your quick response,
I'am running on Lubuntu and I just Installed it with the commands on sdaps.org (added the repo, update and install sdaps)

**Comment by AtlosPrime** [comment]
How can I resolve this issue then?

I created a virtual machine with ubuntu this time, followed every step with no errors, until recognize, and it did the same error:

```
ubun@ubun-VirtualBox:~/Desktop$ sudo sdaps recognize Projet/

------------------------------------------------------------------------------

- SDAPS -- recognize

------------------------------------------------------------------------------

1 sheet

Traceback (most recent call last):                                              
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 126, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/recognize.py", line 57, in recognize
    return recognize.recognize(survey, filter)
  File "/usr/lib/python3/dist-packages/sdaps/recognize/__init__.py", line 32, in recognize
    survey.iterate_progressbar(survey.questionnaire.recognize.recognize, filter)
  File "/usr/lib/python3/dist-packages/sdaps/model/survey.py", line 422, in iterate_progressbar
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sdaps/recognize/buddies.py", line 501, in recognize
    res = self.identify(clean=False)
  File "/usr/lib/python3/dist-packages/sdaps/recognize/buddies.py", line 478, in identify
    self.obj.sheet.recognize.recognize()
  File "/usr/lib/python3/dist-packages/sdaps/recognize/buddies.py", line 83, in recognize
    image.recognize.calculate_rotation()
  File "/usr/lib/python3/dist-packages/sdaps/recognize/buddies.py", line 346, in calculate_rotation
    self.obj.rotated = self.obj.style.get_page_rotation()
  File "/usr/lib/python3/dist-packages/sdaps/recognize/qrcode.py", line 33, in get_page_rotation
    code = self.find_bottom_right_barcode()
  File "/usr/lib/python3/dist-packages/sdaps/recognize/qrcode.py", line 68, in find_bottom_right_barcode
    return read_barcode(self.obj.surface.surface, self.obj.matrix.mm_to_px(),
  File "/usr/lib/python3/dist-packages/sdaps/utils/barcode.py", line 35, in read_barcode
    result = scan(surface, matrix, x, y, width, height, btype)
  File "/usr/lib/python3/dist-packages/sdaps/utils/barcode.py", line 79, in scan
    pbm = image.get_pbm(a1_surface)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by benzea** [comment]
I need to get around to update the package, but I fear I will not really have the time for now (hopefully over the holidays).

For now, I would suggest one of two things:
 1. You can install from sources (i.e. check out the git, install the dependencies, and run `./setup.py build --build-tex` and `./setup.py install --install-tex`
 2. Use Fedora with the copr repository from https://copr.fedorainfracloud.org/coprs/benzea/sdaps/builds/ as that is up-to-date

I suppose, as you already have a VM anyway, using Fedora is likely more convenient. Sorry for all the trouble.

**Comment by AtlosPrime** [comment]
I tried to build it from source, and it's says it's missing a lot of packages (and certains of them aren't "compatible with my current distribution")
Well... I tried again.. With Fedora, and here is the result:

```
Traceback (most recent call last):                                              
  File "/usr/lib64/python3.11/site-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sdaps/script.py", line 126, in decorated_function
    result = function(cmdline)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sdaps/cmdline/recognize.py", line 57, in recognize
    return recognize.recognize(survey, filter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sdaps/recognize/__init__.py", line 32, in recognize
    survey.iterate_progressbar(survey.questionnaire.recognize.recognize, filter)
  File "/usr/lib64/python3.11/site-packages/sdaps/model/survey.py", line 448, in iterate_progressbar
    function(*args, **kwargs)
  File "/usr/lib64/python3.11/site-packages/sdaps/recognize/buddies.py", line 501, in recognize
    res = self.identify(clean=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sdaps/recognize/buddies.py", line 478, in identify
    self.obj.sheet.recognize.recognize()
  File "/usr/lib64/python3.11/site-packages/sdaps/recognize/buddies.py", line 83, in recognize
    image.recognize.calculate_rotation()
  File "/usr/lib64/python3.11/site-packages/sdaps/recognize/buddies.py", line 346, in calculate_rotation
    self.obj.rotated = self.obj.style.get_page_rotation()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sdaps/recognize/qrcode.py", line 33, in get_page_rotation
    code = self.find_bottom_right_barcode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sdaps/recognize/qrcode.py", line 68, in find_bottom_right_barcode
    return read_barcode(self.obj.surface.surface, self.obj.matrix.mm_to_px(),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sdaps/utils/barcode.py", line 35, in read_barcode
    result = scan(surface, matrix, x, y, width, height, btype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/sdaps/utils/barcode.py", line 86, in scan
    proc = subprocess.Popen(['zbarimg', '-q', '-Sdisable', '-S%s.enable' % btype.lower(), tmp], stdout=subprocess.PIPE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'zbarimg'
[fedo@fedora Desktop]$ pip install zbarimg
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement zbarimg (from versions: none)
ERROR: No matching distribution found for zbarimg
```
Yes, I tried to install zbarimg, but the same error, not compatible..

**Comment by AtlosPrime** [comment]
Oh wait! I just installed zbar from [here](http://rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/z/zbar-0.23.90-5.fc38.x86_64.html) and all of his dependencies and recognize worked!
One problem, I opened the gui and.. it recognized nothing? Here a [screenshot](https://ibb.co/8KK1bwS)

**Comment by benzea** [comment]
It recognized it just fine ... it just is in `checkcorrect` mode, and it thought the box was likely filled in because you used a very thick pen. But, it is unsure about it, hence the red box around the checkmarks.

So, use a thinner pen ... or switch the `checkmode` to `check` at the start of the LaTeX file before creating the project.

**Comment by AtlosPrime** [comment]
You were right for the boxes, it recognized just fine! 
 But what can I do for the text? Does it fully support textboxes?

**Comment by AtlosPrime** [comment]
Sorry I just saw in the documentation that fragile content is currently not supported. So, I will adapt it myself
Thank you a lot for this project, and for your responses here!

**Comment by benzea** [comment]
Hmm, what do you mean with the boxes? SDAPS does not do any character recognition, all it does is detect whether or not a box has content and the area of said content (which is then exported as an image). You *can* manually replace this with text using the GUI if this is desired. But, obviously not nice.

Note that the term "fragile" in the documentation has a very technical meaning that is specific to how TeX/LaTeX work.
