### ISSUE TITLE
csvdata_export throws UnicodeEncodeError

### ISSUE THREAD

**Issue by stimon** [sdaps/sdaps#250]
Hi, 

I'm currently running v1.9.10, wrapped in a singularity container. After using the GUI to fill text data having Unicode characters (Norwegian text), the csv export command throws an UnicodeEncodeError:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 126, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/csvdata.py", line 119, in csvdata_export
    csvoptions=csvoptions)
  File "/usr/lib/python3/dist-packages/sdaps/csvdata/__init__.py", line 36, in csvdata_export
    filter,
  File "/usr/lib/python3/dist-packages/sdaps/model/survey.py", line 417, in iterate
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sdaps/csvdata/buddies.py", line 67, in export_data
    self.csv.writerow(data)
  File "/usr/lib/python3.6/csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character '\xf8' in position 485: ordinal not in range(128)
```

It seems like this already happened, but was eventually fixed #23 
Is there anything I can do about this? Should I try to upgrade and build with a more recent version? I the latter case, I wonder if it could give problems with questionnaires built with older versions. 

Thanks!
Santi

**Comment by benzea** [comment]
You can always update SDAPS as there is migration code to for existing projects.

Just be careful that re-creating a survey (i.e. running "setup tex" again) may result in a different "Survey-ID" in SDAPS, causing incompatibilities. However, as long as you have an existing project directory, upgrading SDAPS itself should work fine.

Maybe just make a backup of the survey directory before using it with the newer version and triggering the migration code.

---

Hmm, though this kinda looks like there might have been a regression somehow? That fix is from 2013, so much older than the version you are using.

**Comment by benzea** [comment]
Note that you should *really* update. 1.9.8 introduced a bad bug in the recognition code, and i think that got only fixed in 1.9.12.

**Comment by stimon** [comment]
@benzea to build my Singularity image (based on Ubuntu Bionic), I use the Ubuntu ppa, and it seems like it defaults to 1.9.10. I feared that because I did a build not so long ago and should have included 1.9.12. 

This is an excerpt from the %post 
```
add-apt-repository ppa:benjamin-sipsolutions/sdaps-stable && \
    apt-get update && \
    apt-get install -y sdaps && \
```
After building
```
vagrant@vagrant:/vagrant_data$ singularity exec sdaps.sif sdaps --version
sdaps 1.9.10
```

I also tried specifying the version
```
add-apt-repository ppa:benjamin-sipsolutions/sdaps-stable && \
    apt-get update && \
    apt-get install -y sdaps=1.9.12-1ubuntu1 && \
```
but it fails
```
+ apt-get install -y sdaps=1.9.12-1ubuntu1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.9.12-1ubuntu1' for 'sdaps' was not found
```

Am I doing something wrong?

**Comment by benzea** [comment]
Heh, I suspect no. I only build the sdaps 1.9.12 in the PPA for ubuntu Jammy (kind of figuring that this is a new long-term stable release).

Maybe I need to also build it for older releases ...

**Comment by benzea** [comment]
Oops. Nah, that is a mistake in the package metadata. Should be easy to fix (i.e. replace texlive-generic-recommended with texlive-base). I guess I just never checked that the package was installable, I was happy when it was build successfully.

Not entirely sure when I will get around to fixing that one. However, if you force the installation it will all be fine (dpkg --install --force-depends, iirc).

**Comment by stimon** [comment]
Ok, I think I managed to run the installation that way. I manually installed the dependencies before the dpkg call and only get the warning about texlive-generic-recommended. 

However, I must be missing further steps. I have tried to run the GUI to write and save some Unicode characters to test the CSV export, and it fails to find the main UI file. 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 126, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/gui.py", line 43, in gui
    return gui.gui(survey, cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/gui/__init__.py", line 70, in gui
    MainWindow(provider).run()
  File "/usr/lib/python3/dist-packages/sdaps/gui/__init__.py", line 183, in __init__
    self._builder.add_from_file(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/usr/share/sdaps/ui/main_window.ui”: No such file or directory (4)
```
I checked and under `/usr/share/sdaps/` there is only the `tex` directory. 
Are there any commands or PATH changes after the dpkg installation that I should run?

**Comment by benzea** [comment]
Uhoh. No, I moved the build system with the new version of SDAPS and simply forgot about installing the .ui file.

You can simply copy it to the right location from the repo, sorry for the inconvenience!

**Comment by stimon** [comment]
Thanks Benjamin, that works. Also, the CSV export works fine with Unicode characters too.

**Comment by benzea** [comment]
Really? Funny, I thought nothing should have changed.

I was about to push a change to explicitly open the files with a utf-8 encoding in the cmdline module.

**Comment by benzea** [comment]
Pushed it anyway, it does not hurt ...
