### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ttkrpink** [sdaps/sdaps#257]
Install failed so I am using the  sdaps.py file. The project setup went through. Adding the example failed. The following is the error message. It looks like an OpenCV problem. But I have OpenCV installed already through the apt install. Any help appreciated.

```
setup@MS-OMFLJRHEVXSU:~/tmp/sdaps$ python3 sdaps.py add ./project/ --convert examples/example-scan.pdf
------------------------------------------------------------------------------
- SDAPS -- add
------------------------------------------------------------------------------
Warning: Cannot convert PDF files as poppler is not installed or usable!
Converting input files into a single temporary file.
examples/example-scan.pdf: Not a TIFF or MDI file, bad magic number 20517 (0x5025).
Error: 'NoneType' object has no attribute 'shape'
Error: Running the conversion failed.
Traceback (most recent call last):
  File "/home/setup/tmp/sdaps/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/home/setup/tmp/sdaps/sdaps/script.py", line 126, in decorated_function
    result = function(cmdline)
  File "/home/setup/tmp/sdaps/sdaps/cmdline/add.py", line 112, in add
    convert_images(cmdline['images'], tmp, survey.defs.paper_width, survey.defs.paper_height, cmdline['transform'])
  File "/home/setup/tmp/sdaps/sdaps/convert/__init__.py", line 30, in convert_images
    img = opencv.ensure_orientation(img, portrait)
  File "/home/setup/tmp/sdaps/sdaps/utils/opencv.py", line 189, in ensure_orientation
    img_portrait = img.shape[1] <= img.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```

```
setup@MS-OMFLJRHEVXSU:~/tmp/sdaps$ apt list|grep poppler

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gambas3-gb-poppler/jammy 3.16.3-3 amd64
gir1.2-poppler-0.18/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler-cil-dev/jammy 0.0.3-4.1 all
libpoppler-cil/jammy 0.0.3-4.1 all
libpoppler-cpp-dev/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler-cpp0v5/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler-dev/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler-glib-dev/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler-glib-doc/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 all
libpoppler-glib8/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler-private-dev/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler-qt5-1/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler-qt5-dev/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64
libpoppler118/jammy-security,jammy-updates,now 22.02.0-2ubuntu0.2 amd64 [installed,automatic]
libpopplerkit-dev/jammy 0.0.20051227svn-8.2 amd64
libpopplerkit0/jammy 0.0.20051227svn-8.2 amd64
monodoc-poppler-manual/jammy 0.0.3-4.1 all
poppler-data/jammy,now 0.4.11-1 all [installed]
poppler-utils/jammy-security,jammy-updates,now 22.02.0-2ubuntu0.2 amd64 [installed]
python3-poppler-qt5/jammy 0.75.0-3build2 amd64
qpdfview-pdf-poppler-plugin/jammy 0.4.18-6 amd64
ruby-poppler/jammy 3.4.3-1+ubuntu5 all
zathura-pdf-poppler/jammy 0.3.0-1build1 amd64
```

```
setup@MS-OMFLJRHEVXSU:~/tmp/sdaps$ apt list|grep python3-opencv

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python3-opencv-apps/jammy 2.0.2-6 all
python3-opencv/jammy,now 4.5.4+dfsg-9ubuntu4 amd64 [installed]
```

**Comment by benzea** [comment]
`Warning: Cannot convert PDF files as poppler is not installed or usable!`

PDF support requires the poppler GIR (gobject-introspection) bindings.

**Comment by ttkrpink** [comment]
> `Warning: Cannot convert PDF files as poppler is not installed or usable!`
> 
> PDF support requires the poppler GIR (gobject-introspection) bindings.

gir1.2-poppler-0.18/jammy-security,jammy-updates 22.02.0-2ubuntu0.2 amd64

This package is installed. Any other package is needed?

**Comment by benzea** [comment]
Maybe you are missing python3-gobject?

**Comment by ttkrpink** [comment]
> Maybe you are missing python3-gobject?

yes, indeed.
