### ISSUE TITLE
broken Gui after 1.1.8 update

### ISSUE THREAD

**Issue by fndercole** [sdaps/sdaps#59]
After this (https://github.com/sdaps/sdaps/commit/a36782fa5f8bb5df84dd782092719de34d3cdf89) changes in widgets_buddies.py, the command 

```
sdaps survey gui
```

brings the following error with spanish questions.

```
------------------------------------------------------------------------------
- SDAPS -- gui
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/script.py", line 105, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/cmdline/gui.py", line 43, in gui
    return gui.gui(survey, cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/gui/__init__.py", line 67, in gui
    MainWindow(provider).run()
  File "/usr/lib/python2.7/dist-packages/sdaps/gui/__init__.py", line 184, in __init__
    widgets = provider.survey.questionnaire.widget.create_widget()
  File "/usr/lib/python2.7/dist-packages/sdaps/gui/widget_buddies.py", line 83, in create_widget
    widget = qobject.widget.create_widget()
  File "/usr/lib/python2.7/dist-packages/sdaps/gui/widget_buddies.py", line 144, in create_widget
    self.widget.set_markup('<b>%s %s</b>' % (self.obj.id_str(), GLib.markup_escape_text(self.obj.title)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
```

For the moment, I replace widgets_buddies.py with the previous version, and works fine.

Best

Favio

**Comment by hstarmans** [comment]
Still broken, get the same error: i am able to run the gui of 1.1.7, not 1.1.8 or 1.1.9-1 installed from PPA. I use Ubuntu 14.04.
