### ISSUE TITLE
gui: moving past last/first page and cancel

### ISSUE THREAD

**Issue by FloRinke** [sdaps/sdaps#67]
When moving beyond the first/last page, sdaps gui asks if it should go to the other end of the stack.

Clicking "Cancel" leads to some kind of invalid state: No scanned image is shown, and sometimes the selection pane on the right is all grey until a refresh is triggered by hovering or scrolling the pane (it shows the id of the last selected questionnaire)

**Comment by FloRinke** [comment]
I just noticed this also causes some error output on my console (right after clicking cancel)
````console
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sdaps/gui/sheet_widget.py", line 224, in do_get_preferred_width
    self.hadj.props.upper = self._render_width
  File "/usr/lib64/python2.7/site-packages/sdaps/gui/sheet_widget.py", line 368, in _get_render_width
    image = self.provider.image.surface.surface_rgb
AttributeError: 'Image' object has no attribute 'surface_rgb'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sdaps/gui/sheet_widget.py", line 218, in do_get_preferred_height
    self.vadj.props.upper = self._render_height
  File "/usr/lib64/python2.7/site-packages/sdaps/gui/sheet_widget.py", line 377, in _get_render_height
    image = self.provider.image.surface.surface_rgb
AttributeError: 'Image' object has no attribute 'surface_rgb'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sdaps/gui/sheet_widget.py", line 234, in do_size_allocate
    self.hadj.props.page_size = min(self._render_width, allocation.width)
  File "/usr/lib64/python2.7/site-packages/sdaps/gui/sheet_widget.py", line 368, in _get_render_width
    image = self.provider.image.surface.surface_rgb
AttributeError: 'Image' object has no attribute 'surface_rgb'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sdaps/gui/sheet_widget.py", line 259, in do_draw
    image = self.provider.image.surface.surface_rgb
AttributeError: 'Image' object has no attribute 'surface_rgb'
````
